name: corona_tracker
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  bloc: ^3.0.0
  bloc_test: ^4.0.0
  cupertino_icons: ^0.1.2
  device_preview: ^0.3.0+1
  equatable: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  flutter_cupertino_localizations: ^1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^1.0.3
  flutter_test:
    sdk: flutter
  fluttertoast: ^3.1.3
  get_it: ^4.0.0
  intl: ^0.16.0
  logger: ^0.8.3
  mockito: ^4.1.1
  page_transition: ^1.1.5
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+2
dev_dependencies:
  bloc_test: ^4.0.0
  mockito: ^4.1.1
flutter:
  uses-material-design: true
